# Generated by Django 4.2.3 on 2023-07-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_wishlist_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_dec',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
