# Generated by Django 4.2.3 on 2023-08-05 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRefunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=200)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds_amount', to='app.payment')),
                ('paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds_paid', to='app.payment')),
                ('razorpay_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds_order_id', to='app.payment')),
                ('razorpay_payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds_payment_id', to='app.payment')),
                ('razorpay_payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds_payment_status', to='app.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
