# Generated by Django 4.2.3 on 2023-08-12 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderplaced_payment_status'),
        ('app', '0010_paymentrefunds'),
    ]

    operations = [
    ]
