# Generated by Django 4.2.3 on 2023-08-12 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_20230812_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='https://images-platform.99static.com//EoTfSBmS_p28a4czq1Tv4p4LX44=/0x0:1874x1874/fit-in/500x500/projects-files/116/11621/1162187/ef73b7f7-e727-46c1-9bab-c67a5dab2485.jpg', upload_to='product_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentRefunds',
        ),
    ]
