# Generated by Django 4.2.3 on 2023-08-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_productsimage_delete_paymentrefunds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsimage',
            name='image',
            field=models.FileField(default='https://images-platform.99static.com//EoTfSBmS_p28a4czq1Tv4p4LX44=/0x0:1874x1874/fit-in/500x500/projects-files/116/11621/1162187/ef73b7f7-e727-46c1-9bab-c67a5dab2485.jpg', upload_to='product_images'),
        ),
    ]
